site_name: The Textcamp Guidebook
copyright: Copyright (c) 2020, Peat Bakke <peat@text.camp>
docs_dir: src
site_dir: docs
nav:
  - Home: index.md
  - The Guides:
    - Player's Guide: players/index.md
    - Creator's Guide: creators/index.md
    - Developer's Guide: developers/index.md
  - About:
    - Code of Conduct: about/code_of_conduct.md
    - License: about/license.md
